### PR TITLE
move mocha and chai to devDependencies

### PR DESCRIPTION
**Pull request by akatov**

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]
OH NO! Thank you for fixing!

**Comment by rwjblue** [comment]
Released as 0.1.1, thank you!

**Comment by akatov** [comment]
there's already a version `0.2.0` which is currently required by ember-cli 3.1.1 though....

**Comment by akatov** [comment]
@rwjblue could you release this as version 0.2.1 also?

**Comment by rwjblue** [comment]
Also released 0.2.1, sorry about that 😢

**Pull request merged**
